### ISSUE TITLE
Error when parsing PDF page

### ISSUE THREAD

**Issue by rerik** [xavctn/img2table#141]
Hello! I've got an error when trying to parse PDF document page.
```
Traceback (most recent call last):
  File "<MyProjectFile>.py", line <LineNumber>, in MyFunc
    <MyVar> = image.extract_tables(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "<MyProjectPath>/venv/lib/python3.11/site-packages/img2table/document/image.py", line 42, in extract_tables
    extracted_tables = super(Image, self).extract_tables(ocr=ocr,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<MyProjectPath>/venv/lib/python3.11/site-packages/img2table/document/base/__init__.py", line 123, in extract_tables
    tables = {idx: TableImage(img=img,
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<MyProjectPath>/venv/lib/python3.11/site-packages/img2table/document/base/__init__.py", line 124, in <dictcomp>
    min_confidence=min_confidence).extract_tables(implicit_rows=implicit_rows,
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<MyProjectPath>/venv/lib/python3.11/site-packages/img2table/tables/image.py", line 124, in extract_tables
    self.extract_bordered_tables(implicit_rows=implicit_rows)
  File "<MyProjectPath>/venv/lib/python3.11/site-packages/img2table/tables/image.py", line 62, in extract_bordered_tables
    self.thresh = threshold_dark_areas(img=self.img, char_length=self.char_length)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<MyProjectPath>/venv/lib/python3.11/site-packages/img2table/tables/processing/bordered_tables/lines.py", line 42, in threshold_dark_areas
    margin = int(char_length)
             ^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

I can give you my case to reproduce an error if you need, but it seems like the bug is on the surface. Argument **char_length** of **threshold_dark_areas** function annotated with **Optional**, but there is no handling of **None** value on line 42.

**Comment by xavctn** [comment]
Hi,
Thanks for your feedback, I just corrected this issue and it should now be working with the latest release of the library.
