### ISSUE TITLE
Error in tables/processing/bordered_tables/tables/table_creation.py:72, in remove_unwanted_elements

### ISSUE THREAD

**Issue by rerik** [xavctn/img2table#149]
```
Traceback (most recent call last):
  File "<MyScript>.py", line 355, in extract_tables
    extracted_tables = image.extract_tables(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "<MyProject>/venv/lib/python3.11/site-packages/img2table/document/image.py", line 42, in extract_tables
    extracted_tables = super(Image, self).extract_tables(ocr=ocr,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<MyProject>/venv/lib/python3.11/site-packages/img2table/document/base/__init__.py", line 126, in extract_tables
    tables = {idx: TableImage(img=img,
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<MyProject>/venv/lib/python3.11/site-packages/img2table/document/base/__init__.py", line 127, in <dictcomp>
    min_confidence=min_confidence).extract_tables(implicit_rows=implicit_rows,
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<MyProject>/venv/lib/python3.11/site-packages/img2table/tables/image.py", line 128, in extract_tables
    self.extract_borderless_tables()
  File "<MyProject>/venv/lib/python3.11/site-packages/img2table/tables/image.py", line 106, in extract_borderless_tables
    borderless_tbs = identify_borderless_tables(thresh=self.thresh,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<MyProject>/venv/lib/python3.11/site-packages/img2table/tables/processing/borderless_tables/__init__.py", line 69, in identify_borderless_tables
    borderless_table = identify_table(columns=column_group,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<MyProject>/venv/lib/python3.11/site-packages/img2table/tables/processing/borderless_tables/table/__init__.py", line 23, in identify_table
    table = get_table(columns=columns,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<MyProject>/venv/lib/python3.11/site-packages/img2table/tables/processing/borderless_tables/table/table_creation.py", line 72, in get_table
    table = cluster_to_table(cluster_cells=list_cells, elements=contours, borderless=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<MyProject>/venv/lib/python3.11/site-packages/img2table/tables/processing/bordered_tables/tables/table_creation.py", line 133, in cluster_to_table
    processed_table = remove_unwanted_elements(table=table, elements=elements)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<MyProject>/venv/lib/python3.11/site-packages/img2table/tables/processing/bordered_tables/tables/table_creation.py", line 72, in remove_unwanted_elements
    .collect()
     ^^^^^^^^^
  File "<MyProject>/venv/lib/python3.11/site-packages/polars/utils/deprecation.py", line 100, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<MyProject>/venv/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1788, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
polars.exceptions.ColumnNotFoundError: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN

Error originated just after this operation:
ErrorStateSync(AlreadyEncountered(not found: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN))
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN

Error originated just after this operation:
ErrorStateSync(AlreadyEncountered(not found: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN

Error originated just after this operation:
ErrorStateSync(AlreadyEncountered(not found: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN))
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN))
ErrorStateSync(AlreadyEncountered(not found: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN))
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN

Error originated just after this operation:
ErrorStateSync(AlreadyEncountered(not found: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN

Error originated just after this operation:
ErrorStateSync(AlreadyEncountered(not found: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN))
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN

Error originated just after this operation:
ErrorStateSync(AlreadyEncountered(not found: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN

Error originated just after this operation:
ErrorStateSync(AlreadyEncountered(not found: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN))
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN))
ErrorStateSync(AlreadyEncountered(not found: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN))
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN))
ErrorStateSync(AlreadyEncountered(not found: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN

Error originated just after this operation:
ErrorStateSync(AlreadyEncountered(not found: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN))
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN))
ErrorStateSync(AlreadyEncountered(not found: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN))
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN

Error originated just after this operation:
ErrorStateSync(AlreadyEncountered(not found: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN

Error originated just after this operation:
ErrorStateSync(AlreadyEncountered(not found: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN))
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN

Error originated just after this operation:
ErrorStateSync(AlreadyEncountered(not found: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN

Error originated just after this operation:
ErrorStateSync(AlreadyEncountered(not found: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN))
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN))
ErrorStateSync(AlreadyEncountered(not found: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN))
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN

Error originated just after this operation:
ErrorStateSync(AlreadyEncountered(not found: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN

Error originated just after this operation:
ErrorStateSync(AlreadyEncountered(not found: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN))
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN

Error originated just after this operation:
ErrorStateSync(AlreadyEncountered(not found: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN

Error originated just after this operation:
ErrorStateSync(AlreadyEncountered(not found: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN))
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN))
ErrorStateSync(AlreadyEncountered(not found: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN))
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN))
ErrorStateSync(AlreadyEncountered(not found: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN

Error originated just after this operation:
ErrorStateSync(AlreadyEncountered(not found: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN))
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN))
ErrorStateSync(AlreadyEncountered(not found: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN))
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN))
ErrorStateSync(AlreadyEncountered(not found: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN

Error originated just after this operation:
ErrorStateSync(AlreadyEncountered(not found: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN))
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN

Error originated just after this operation:
ErrorStateSync(AlreadyEncountered(not found: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN

Error originated just after this operation:
ErrorStateSync(AlreadyEncountered(not found: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN))
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN))
ErrorStateSync(AlreadyEncountered(not found: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN))
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN))
ErrorStateSync(AlreadyEncountered(not found: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN

Error originated just after this operation:
ErrorStateSync(AlreadyEncountered(not found: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN))
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN))
ErrorStateSync(AlreadyEncountered(not found: x2

Error originated just after this operation:
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN))
CROSS JOIN:
LEFT PLAN ON: []
  DF []; PROJECT */0 COLUMNS; SELECTION: "None"
RIGHT PLAN ON: []
  DF ["x1_el", "y1_el", "x2_el", "y2_el"]; PROJECT */5 COLUMNS; SELECTION: "None"
END CROSS JOIN
```

**Comment by xavctn** [comment]
Hello,
This should be fixed (as well as the other bugs you reported) by some modifications I made that should be included in the next release 👍

**Comment by rerik** [comment]
Thank you!!!
