### ISSUE TITLE
Attribute error: 'ExprArrayNameSpace' object has no attribute 'lengths'

### ISSUE THREAD

**Issue by GamovSP** [xavctn/img2table#61]
While trying to run next code:
----------------------------------------------------------------------------------------------
from img2table.document import Image
from img2table.ocr import TesseractOCR
import os

ocr = TesseractOCR(n_threads=1, lang='rus')
print(os.path.exists(r'C:\Users\админ\PycharmProjects\pythonProject8\grebla_1.jpg'))
image = Image(src=r'C:\Users\админ\PycharmProjects\pythonProject8\grebla_1.jpg',
              detect_rotation=True)

extraction = image.extract_tables(ocr=ocr, implicit_rows=False)
image.to_xlsx(dest=r"C:\Users\админ\PycharmProjects\pythonProject8\hehe.xlsx", ocr=ocr, implicit_rows=False, borderless_tables=False)
----------------------------------------------------------------------------------------------
I'm getting this:
----------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\pythonProject8\dudu.py", line 12, in <module>
    extraction = image.extract_tables(ocr=ocr, implicit_rows=False)
  File "C:\Users\админ\PycharmProjects\pythonProject8\venv\lib\site-packages\img2table\document\image.py", line 41, in extract_tables
    extracted_tables = super(Image, self).extract_tables(ocr=ocr,
  File "C:\Users\админ\PycharmProjects\pythonProject8\venv\lib\site-packages\img2table\document\base\__init__.py", line 71, in extract_tables
    tables = {idx: TableImage(img=img,
  File "C:\Users\админ\PycharmProjects\pythonProject8\venv\lib\site-packages\img2table\document\base\__init__.py", line 71, in <dictcomp>
    tables = {idx: TableImage(img=img,
  File "C:\Users\админ\PycharmProjects\pythonProject8\venv\lib\site-packages\img2table\tables\image.py", line 136, in extract_tables
    self.extract_bordered_tables(implicit_rows=implicit_rows)
  File "C:\Users\админ\PycharmProjects\pythonProject8\venv\lib\site-packages\img2table\tables\image.py", line 86, in extract_bordered_tables
    cells = get_cells(horizontal_lines=h_lines,
  File "C:\Users\админ\PycharmProjects\pythonProject8\venv\lib\site-packages\img2table\tables\processing\bordered_tables\cells\__init__.py", line 18, in get_cells
    df_cells = get_cells_dataframe(horizontal_lines=horizontal_lines,
  File "C:\Users\админ\PycharmProjects\pythonProject8\venv\lib\site-packages\img2table\tables\processing\bordered_tables\cells\identification.py", line 107, in get_cells_dataframe
    .filter(pl.col("dels").arr.lengths() >= 2)
AttributeError: 'ExprArrayNameSpace' object has no attribute 'lengths'
----------------------------------------------------------------------------------------------
The table I try to extract is not too complicated and has borders. What am I supposed to do with that? Thank you

**Comment by jeni1616** [comment]
Yes, I am getting this same error. any solution?

**Comment by osBins** [comment]
Getting the same error

**Comment by GamovSP** [comment]
Well, I went to the identidication.py and put the conflicting expression in the comment. Now it works, but I would like to know what this expression does and was it a bad descision to kick it out from the script :\ 
![image](https://github.com/xavctn/img2table/assets/129841995/e0fb6022-b66b-40b6-93d1-c09cce76b775)

**Comment by xavctn** [comment]
Hi,
I will check it, it seems like it is an issue related to one of the latest version of polars.

**Comment by osBins** [comment]
Thank you!

**Comment by xavctn** [comment]
It is fixed, I just created a new release patching the issue
