### ISSUE TITLE
Google Vision Instance is throwing an exception

### ISSUE THREAD

**Issue by pultzlucas** [xavctn/img2table#76]
Hello!
I'm trying to use the google vision instance from the lib to my project

Here is the code "main.py"...
````py
from img2table.document import Image
from img2table.ocr import VisionOCR

src = r'imgs/1.jpeg'
image = Image(src, detect_rotation=False)

ocr = VisionOCR(api_key='MY_API_KEY')

extracted_tables = image.extract_tables(ocr=ocr)

print(extracted_tables)
````

but it's throwing this error...

````
Traceback (most recent call last):
  File "C:\Users\NAPP\Desktop\reps\products-ocr-vision\table.py", line 9, in <module>
    extracted_tables = image.extract_tables(ocr=ocr)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NAPP\AppData\Roaming\Python\Python311\site-packages\img2table\document\image.py", line 41, in extract_tables
    extracted_tables = super(Image, self).extract_tables(ocr=ocr,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NAPP\AppData\Roaming\Python\Python311\site-packages\img2table\document\base\__init__.py", line 67, in 
extract_tables
    self.ocr_df = ocr.of(document=self)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NAPP\AppData\Roaming\Python\Python311\site-packages\img2table\ocr\base.py", line 40, in of
    content = self.content(document=document)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NAPP\AppData\Roaming\Python\Python311\site-packages\img2table\ocr\google_vision.py", line 238, in content
    return self.content_getter.get_content(document=document)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NAPP\AppData\Roaming\Python\Python311\site-packages\img2table\ocr\google_vision.py", line 123, in get_content
    for ocr in pool.map(lambda d: self.get_ocr_image(*d), args):
  File "C:\Python311\Lib\concurrent\futures\_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\concurrent\futures\_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NAPP\AppData\Roaming\Python\Python311\site-packages\img2table\ocr\google_vision.py", line 123, in <lambda>
    for ocr in pool.map(lambda d: self.get_ocr_image(*d), args):
                                  ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NAPP\AppData\Roaming\Python\Python311\site-packages\img2table\ocr\google_vision.py", line 111, in get_ocr_image
    return self.map_response(response=response, page=page)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NAPP\AppData\Roaming\Python\Python311\site-packages\img2table\ocr\google_vision.py", line 64, in map_response
    "x1": min(map(lambda el: el.get('x'), word.get('boundingBox').get('vertices'))),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'int' and 'NoneType'
````

**Comment by xavctn** [comment]
Hi,
Seems like Google Vision does not always return x or y coordinates of vertices when the bounding box of the word is on the edge of the image.
I will fix this

**Comment by pultzlucas** [comment]
ok, thanks!!!
